### ISSUE TITLE
Produce a linkable badge like travis-ci does

### ISSUE THREAD

**Issue by ralphbean** [ralphbean/pep8bot#19]
so users can display us proudly in their README.  :)

**Comment by pypingou** [comment]
README, website, twitter, facebook, g+, linkedin :sparkles: let's not be restrictive ;-)

**Comment by ralphbean** [comment]
Might want to look into shields or buckler for this - http://blog.repl.ca/2013/08/buckler-v100.html

**Comment by pypingou** [comment]
I tried having a look at this but apparently we do not store the results of the pep8 run in the database.
I think this would be the first step. Then we could do something like `/shield/username/reponame` that would return the appropriate image using buckler.

We will probably have to define some threshold for green/orange/red, I'd propose the first threshold to be at 10 or 15, and the second 75 or 100 maybe.

**Comment by ralphbean** [comment]
I've been thinking some recently on how pep8.me has limited value because of how github only allows one "status" tag on a pull request at a time -- travis-ci and pep8.me fight for who gets to appear in the UI.

Even with that being the case, the shields/badges proposed in this ticket would make pep8.me worth reviving as a project since we could actually display the status consistently somewhere.

**Comment by ralphbean** [comment]
@pypingou we do actually store the results of the pep8 run in the database, which is how we are able to generate pages like this one:

http://pep8.me/fedora-infra/fedmsg/commits/ef2599d311692b5c526db44ce670755ccc5afacd

This `Commit` model has the pep8 errors and the error count:

https://github.com/ralphbean/pep8bot/blob/develop/pep8bot/models/__init__.py#L212

**Comment by pypingou** [comment]
nice :)
